name: Dataset (NERC grant)
description: Add a NERC grant dataset.
title: "<NERC ID: Working dataset title>"

body:
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: What is known about this dataset so far?
    validations:
      required: false

  - type: checkboxes
    id: tasks
    attributes:	 
      label: Tasks 
      options:
        - label: Change status to *Data due* (GitHub)
        - label: Update *Data delivery expected* field (GitHub)
        - label: Data in arrivals (Arrivals)
        - label: Change status to *Archiving in progress* (GitHub)
        - label: Update *Data delivered* field (GitHub)
        - label: Check data meet archival standards
        - label: Ingest data using cedaarchive (Ingest)
        - label: Create MOLES records (MOLES Admin)
        - label: Add MOLES record links to parent issue (GitHub)
        - label: Send MOLES records for PI sign-off (saved reply 04.02) (Help Scout)
        - label: Send MOLES records for internal review (MOLES Admin)
        - label: Send confirmation of internal review (saved reply 04.03) (Help Scout)
        - label: Complete MOLES review actions (MOLES Admin)
        - label: Publish MOLES records (MOLES Admin)
        - label: Change status to *Archiving completed* (GitHub)
    validations:
      required: true
