name: NERC grant
description: Add a NERC grant.
title: "Add grant title"
labels: ["Project"]
projects: ["cedadev/139"]
body:
  - type: markdown
    attributes:
      value: |
        This form populates the body of the issue. Additional fields are available once the issue is open. Leave any section blank to add later.
  - type: input
    id: datamad_link
    attributes:
      label: DataMad
      description: Link to DataMad page.
      placeholder: ex. https://datamad.ceda.ac.uk/grant/xxxx
    validations:
      required: false
  - type: input
    id: helpscout_link
    attributes:
      label: Help Scout
      description: Link to HelpScout conversation.
      placeholder: ex. https://secure.helpscout.net/conversation/xxxx
    validations:
      required: false
  - type: input
    id: dsw_link
    attributes:
      label: DSW
      description: Link to DSW project.
      placeholder: ex. https://nerceds.fair-wizard.com/wizard/projects/xxxx
    validations:
      required: false
  - type: textarea
    id: project_description
    attributes:
      label: Project description
      description: Project description from DataMad.
      placeholder: ...
    validations:
      required: false