name: NERC grant
description: Add a NERC grant.
title: "<Add grant title here (e.g. NERC ref:Title)>"
labels: ["Project"]
projects: ["cedadev/139"]
body:

  - type: markdown
    attributes:
      value: |
        ✨ Create a new issue by adding a title above
        📝 Fill in the details below (or leave as is to edit later)
        🌱 Additional fields are available once the issue is open

  - type: textarea
    attributes:
      label: Issue details
      value: |
        **DataMad:** _e.g. datamad.ceda.ac.uk/grant/xxxx_
        **Help Scout:** _e.g. helpscout.net/conversation/xxxx_
        **DSW:** _e.g. nerceds.fair-wizard.com/projects/xxxx_

        **Description:**
        _Project description from DataMad_
    validations:
      required: false