name: non-NERC project
description: Add a non-NERC project.
title: "Add project title"
labels: ["Project"]
projects: ["cedadev/139"]
body:
  - type: markdown
    attributes:
      value: |
        This form populates the body of the issue. Additional fields are available once the issue is open. Leave any section blank to add later.
  - type: input
    id: helpscout_link
    attributes:
      label: Help Scout
      description: Link to HelpScout conversation.
      placeholder: ex. https://secure.helpscout.net/conversation/xxxx
    validations:
      required: false
  - type: input
    id: dsw_link
    attributes:
      label: DSW
      description: Link to DSW project.
      placeholder: ex. https://nerceds.fair-wizard.com/wizard/projects/xxxx
    validations:
      required: false
  - type: textarea
    id: project_description
    attributes:
      label: Project description
      description: Short description of the project.
      placeholder: ...
    validations:
      required: false