name: non-NERC project
description: Add a non-NERC project.
title: "<e.g. Project ref:Title>"
labels: ["Project"]
projects: ["cedadev/139"]
body:

  - type: markdown
    attributes:
      value: |
        ✨ Create a new issue by adding a title above
        📝 Fill in the details below (or leave as is to edit later)
        🌱 Additional fields are available once the issue is open

  - type: textarea
    attributes:
      label: Project details
      value: |
        **Project webpage (?):** _<e.g. datamad.ceda.ac.uk/grant/xxxx>_
        **Help Scout:** _<e.g. helpscout.net/conversation/xxxx>_
        **DSW (?):** _<e.g. nerceds.fair-wizard.com/projects/xxxx>_

        **Description:**
        _<Short description of the project>_
    validations:
      required: false
