name: Dataset
description: Create a dataset sub-issue
title: "<NERC ID: Working dataset title>"

labels:
  - Dataset

body:
  - type: markdown
    attributes:
      value: |
        ## Dataset Sub-Issue

        **Status:** Data due

  - type: input
    id: dataset_name
    attributes:
      label: Dataset name
      placeholder: Enter dataset name
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the dataset and any relevant context.
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Tasks
      value: |
        - [ ] Change status to *Archiving in progress* (GitHub)
        - [ ] Data in arrivals (Arrivals)
        - [ ] Update *Data delivered* field (GitHub)
        - [ ] Check data meet archival standards
        - [ ] Ingest data using cedaarchive (Ingest)
        - [ ] Create MOLES records (MOLES Admin)
        - [ ] Add MOLES record links to parent issue (GitHub)
        - [ ] Send MOLES records for PI sign-off (saved reply 04.02) (Help Scout)
        - [ ] Send MOLES records for internal review (MOLES Admin)
        - [ ] Send confirmation of internal review (saved reply 04.03) (Help Scout)
        - [ ] Complete MOLES review actions (MOLES Admin)
        - [ ] Publish MOLES records (MOLES Admin)
        - [ ] Change status to *Archiving completed* (GitHub)
    validations:
      required: true
