name: Dataset
description: Add a dataset. Only add datasets as sub-issues within a NERC grant or non-NERC project.
title: "Add dataset working title"
labels: ["Dataset"]
projects: ["cedadev/139"]
body:

  - type: markdown
    attributes:
      value: |
        Create a dataset sub-issue by adding a title above, and filling in the details below (or leave blank to add these later). 
        Additional fields are available once the sub-issue is open.

  - type: textarea
    attributes:
      label: Issue details
      value: |
        **Dataset contact name:** _paste text here_
        **Datset contact email:** _paste text here_
        **File format:** _paste text here_
        **Expected volume:** _paste text here_

        **Dataset description:**
        _paste text here_
    validations:
      required: false