name: Dataset
description: Add a dataset. Only add datasets as sub-issues within a NERC grant or non-NERC project.
title: "Add dataset working title"
labels: ["Dataset"]
projects: ["cedadev/139"]
body:

  - type: markdown
    attributes:
      value: |
        ✨ Create a new dataset sub-issue by adding a title above
        📝 Fill in the details below (or leave as is to edit later)
        🌱 Additional fields are available once the sub-issue is open

  - type: textarea
    attributes:
      label: Issue details
      value: |
        **Dataset contact name:** _e.g. Contact Name_
        **Datset contact email:** _e.g. email@example.com_
        **File format:** _e.g. netCDF, BADC-CSV_
        **Expected volume:** _e.g. 10TB_

        **Dataset description:**
        _Short description of the dataset_
    validations:
      required: false