name: Grant
description: File a bug report.
title: "[Grant]: "
labels: ["Grant"]
projects: ["cedadev/139"]
assignees:
  - wendygarland
body:
  - type: markdown
    attributes:
      value: |
        test text...
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
