# This workflow triggers when an issue comment is posted.
# It checks for comments entered as "/remind [who] [what] [when]"
# and creates new reminders from any matching comments

name: Create new reminder

permissions:
  issues: write

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check for and create new reminders
        uses: agrc/create-reminder-action@v1
