# This workflow checks for and creates new reminders entered as "/remind [who] [what] [when]" in issue comments

name: create new reminder

permissions:
  issues: write

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Check for and create new reminders
        uses: agrc/create-reminder-action@v1
