# This is a test action to check the inactive workflow functionality
# For more information, see: https://github.com/actions/stale
name: test inactive workflow

on:
  schedule:
  - cron: '50 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity for 14 days. Update issue to reset timer.'
        stale-issue-label: '14-days-inactive'
        days-before-stale: 14
        days-before-close: -1
        remove-stale-when-updated: true
